\ TARGET TESTING

TARGET KERNEL PRAM
RELOAD  CR CR GREET

SET-DOWNLOAD

INCLUDE %SWIFTX\SRC\CONICAL     \ Conical piles demo
INCLUDE %SWIFTX\SRC\DUMB        \ Dumb terminal


0 TERMINAL CONSOLE

: DEMO ( -- )   CONSOLE ACTIVATE
   DUMB  COM1 SCI-TERMINAL
   BEGIN  CALCULATE  AGAIN ;

DOWNLOAD-ALL

@LAST LAST !
CONSOLE CONSTRUCT  DEMO
